### ISSUE TITLE
HashCodeVisitor Ignores Comments when Generating Hashcode

### ISSUE THREAD

**Issue by ryan-beckett** [javaparser/javaparser#1147]
The following test passes and it shouldn't considering `HashCodeVisitor` uses comments to generate a hash code.

```
    @Test
    public void testHashCodeEqualsWithDifferentComments() {
        CompilationUnit p1 = JavaParser.parse("/* a */ class X { /** b */} //c");
        CompilationUnit p2 = JavaParser.parse("/* b */ class X { }  //c");
        assertEquals(p1.hashCode(), p2.hashCode());
        assertEquals(p1.getComments().size(), 3);
        assertEquals(p2.getComments().size(), 2);
    }
```

**Comment by matozoid** [comment]
Ah, it's what I expected: our mediocre comment support. Here's what your YAML export tells me:

p1 looks like this:
```yaml
root: 
    types: 
        - type: 
            isInterface: "false"
            name: 
                identifier: "X"
            comment: 
                content: "c"
```

p2 looks like this:
```yaml
root: 
    types: 
        - type: 
            isInterface: "false"
            name: 
                identifier: "X"
            comment: 
                content: "c"
```

Exactly the same, because the comment attribution algorithm hasn't managed to assign the other comments to nodes. I'm a little surprised about the starting comments not being attributed to the class, but whatever - for 4.0.0 I'm going to rework all comment support to take a completely different approach (you've probably seen the issue.)
