### ISSUE TITLE
Adding the private field ArrayList<String> to a class.

### ISSUE THREAD

**Issue by AlexMackechnieOld** [javaparser/javaparser#1189]
Can't find a way of adding a private field `ArrayList<String> array = new ArrayList<String>();` to a class. Tried using a class visitor and FieldDeclaration, but only luck with adding primitive types (which end up at the bottom of a class instead of the top).

**Comment by matozoid** [comment]
Here's the easy way out:
```java
CompilationUnit cu = parse("class X{}");
cu.getClassByName("X").ifPresent( coid -> coid.addMember(parseBodyDeclaration("private ArrayList<String> array = new ArrayList<String>();")));
```

**Comment by matozoid** [comment]
This tells me how the field declaration is constructed:
```java
BodyDeclaration<?> field = parseBodyDeclaration("private ArrayList<String> array = new ArrayList<String>();");
System.out.println(new YamlPrinter(true).output(field));
```

```yaml
root(Type=FieldDeclaration): 
    variables: 
        - variable(Type=VariableDeclarator): 
            initializer(Type=ObjectCreationExpr): 
                type(Type=ClassOrInterfaceType): 
                    name(Type=SimpleName): 
                        identifier: "ArrayList"
                    typeArguments: 
                        - typeArgument(Type=ClassOrInterfaceType): 
                            name(Type=SimpleName): 
                                identifier: "String"
            name(Type=SimpleName): 
                identifier: "array"
            type(Type=ClassOrInterfaceType): 
                name(Type=SimpleName): 
                    identifier: "ArrayList"
                typeArguments: 
                    - typeArgument(Type=ClassOrInterfaceType): 
                        name(Type=SimpleName): 
                            identifier: "String"
```
