### ISSUE TITLE
How can I add a method call to the builder pattern

### ISSUE THREAD

**Issue by auzatsepin** [javaparser/javaparser#1314]
Hi!

I can't understand how i can add method to method chains.
I override ModifierVisitor method visit(n: MethodCallExpr, arg: ClassModel) and can create new MethodCallExpr, but all I can do is call setParentNode method, but it just add new MethodCallExpr to the end of child nodes.

What is right way do it ?

For example i have a class
```java
public class Builder {

    private String a;
    private String b;

    public Builder withA(String a) {
        this.a = a;
        return this;
    }

    public Builder withB(String b) {
        this.b = b;
        return this;
    }

    public A build() {
        return new A();
    }
}
```
and an abstract class that uses it
```java
public abstract class Generator {

    public A generate() {
        return new Builder()
                .build();
    }
}
```
i want to generate something like 
```java
public class Generated extends Generator {
    public A generate() {
       return Builder()
                .withA("a")
                .withB("b")
                .build();
    }
}
```

how do i add a method correctly ?

**Comment by matozoid** [comment]
When I run...
```java
import com.github.javaparser.JavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.printer.YamlPrinter;

public class Test {
    public static void main(String[] args) {
        CompilationUnit cu = JavaParser.parse("public class Generated extends Generator {\n" +
                "    public A generate() {\n" +
                "       return Builder()\n" +
                "                .withA(\"a\")\n" +
                "                .withB(\"b\")\n" +
                "                .build();\n" +
                "    }\n" +
                "}");
        System.out.println(new YamlPrinter(true).output(cu));
    }
}
```
the output is
```yaml
root(Type=CompilationUnit): 
    types: 
        - type(Type=ClassOrInterfaceDeclaration): 
            isInterface: "false"
            name(Type=SimpleName): 
                identifier: "Generated"
            extendedTypes: 
                - extendedType(Type=ClassOrInterfaceType): 
                    name(Type=SimpleName): 
                        identifier: "Generator"
            members: 
                - member(Type=MethodDeclaration): 
                    body(Type=BlockStmt): 
                        statements: 
                            - statement(Type=ReturnStmt): 
                                expression(Type=MethodCallExpr): 
                                    name(Type=SimpleName): 
                                        identifier: "build"
                                    scope(Type=MethodCallExpr): 
                                        name(Type=SimpleName): 
                                            identifier: "withB"
                                        scope(Type=MethodCallExpr): 
                                            name(Type=SimpleName): 
                                                identifier: "withA"
                                            scope(Type=MethodCallExpr): 
                                                name(Type=SimpleName): 
                                                    identifier: "Builder"
                                            arguments: 
                                                - argument(Type=StringLiteralExpr): 
                                                    value: "a"
                                        arguments: 
                                            - argument(Type=StringLiteralExpr): 
                                                value: "b"
                    type(Type=ClassOrInterfaceType): 
                        name(Type=SimpleName): 
                            identifier: "A"
                    name(Type=SimpleName): 
                        identifier: "generate"
```
... which tells me that you build chains of `MethodCallExpr` by using its `scope` field.
