### ISSUE TITLE
Better aproach to handle a list of annotations

### ISSUE THREAD

**Issue by cunhazera** [javaparser/javaparser#1343]
I'm having to parse a list of annotations like this:

``` java
    @ApiResponses({
            @ApiResponse(code = 200, message = "Ok", response = TaskCollectionResponse.class),
            @ApiResponse(code = 400, message = "Failed to list tasks, see response for more details", response = ErrorResponse.class),
            @ApiResponse(code = 401, message = "Not authorized", response = ErrorResponse.class),
            @ApiResponse(code = 500, message = "Internal error, see response for more details", response = ErrorResponse.class)
    })
    public Response findAll() {
        return Response.ok(resp).build();
    }
```

But I'm facing some problems to parse the @ApiResponse, that is inside the @ApiResponses. I can not get the properties and etc.

Is there already some way to do this?

**Comment by matozoid** [comment]
Try using the techniques found here: https://matozoid.github.io/2017/12/13/inspecting-an-ast.html

**Comment by matozoid** [comment]
@cunhazera did you figure it out?

**Comment by cunhazera** [comment]
@matozoid No :(

Can you help me?

**Comment by matozoid** [comment]
Show me the Yaml AST you got and I'll tell you how to use it to answer this question.

**Comment by cunhazera** [comment]
I have no Yaml, I only have the java code, as the one I wrote above.

**Comment by cunhazera** [comment]
I'm doing this actually: `List<String> responses = method.getAnnotationByName("ApiResponses").get();`

But I can not access the annotations inside of `ApiResponses`

**Comment by matozoid** [comment]
Did you read the article? It shows how to get the Yaml.

**Comment by cunhazera** [comment]
Parse the Yaml is not useful for me, I guess.

**Comment by matozoid** [comment]
No it isn't, but the Yaml is useful to study, to see how you can get the information you need. If you put the Yaml here, I can tell you how to read it.

**Comment by cunhazera** [comment]
The final YAML from my java file has 2755 lines. May I put it here?

**Comment by matozoid** [comment]
Sure!

**Comment by cunhazera** [comment]
Imma put it as a file.

**Comment by cunhazera** [comment]
[final.txt](https://github.com/javaparser/javaparser/files/1647263/final.txt)

**Comment by matozoid** [comment]
I searched for `TaskCollectionResponse` to find this part:
```yaml
                    annotations: 
                        - annotation(Type=MarkerAnnotationExpr): 
                            name(Type=Name): 
                                identifier: "GET"
                        - annotation(Type=MarkerAnnotationExpr): 
                            name(Type=Name): 
                                identifier: "PermitAll"
                        - annotation(Type=NormalAnnotationExpr): 
                            name(Type=Name): 
                                identifier: "ApiOperation"
                            pairs: 
                                - pair(Type=MemberValuePair): 
                                    name(Type=SimpleName): 
                                        identifier: "value"
                                    value(Type=StringLiteralExpr): 
                                        value: "Returns existing tasks"
                        - annotation(Type=SingleMemberAnnotationExpr): 
                            memberValue(Type=ArrayInitializerExpr): 
                                values: 
                                    - value(Type=NormalAnnotationExpr): 
                                        name(Type=Name): 
                                            identifier: "ApiResponse"
                                        pairs: 
                                            - pair(Type=MemberValuePair): 
                                                name(Type=SimpleName): 
                                                    identifier: "code"
                                                value(Type=IntegerLiteralExpr): 
                                                    value: "200"
                                            - pair(Type=MemberValuePair): 
                                                name(Type=SimpleName): 
                                                    identifier: "message"
                                                value(Type=StringLiteralExpr): 
                                                    value: "Ok"
                                            - pair(Type=MemberValuePair): 
                                                name(Type=SimpleName): 
                                                    identifier: "response"
                                                value(Type=ClassExpr): 
                                                    type(Type=ClassOrInterfaceType): 
                                                        name(Type=SimpleName): 
                                                            identifier: "TaskCollectionResponse"
                                    - value(Type=NormalAnnotationExpr): 
                                        name(Type=Name): 
                                            identifier: "ApiResponse"
                                        pairs: 
                                            - pair(Type=MemberValuePair): 
                                                name(Type=SimpleName): 
                                                    identifier: "code"
                                                value(Type=IntegerLiteralExpr): 
                                                    value: "400"
                                            - pair(Type=MemberValuePair): 
                                                name(Type=SimpleName): 
                                                    identifier: "message"
                                                value(Type=StringLiteralExpr): 
                                                    value: "Failed to list tasks, see response for more details"
                                            - pair(Type=MemberValuePair): 
                                                name(Type=SimpleName): 
                                                    identifier: "response"
                                                value(Type=ClassExpr): 
                                                    type(Type=ClassOrInterfaceType): 
                                                        name(Type=SimpleName): 
                                                            identifier: "ErrorResponse"
                                    - value(Type=NormalAnnotationExpr): 
                                        name(Type=Name): 
                                            identifier: "ApiResponse"
                                        pairs: 
                                            - pair(Type=MemberValuePair): 
                                                name(Type=SimpleName): 
                                                    identifier: "code"
                                                value(Type=IntegerLiteralExpr): 
                                                    value: "401"
                                            - pair(Type=MemberValuePair): 
                                                name(Type=SimpleName): 
                                                    identifier: "message"
                                                value(Type=StringLiteralExpr): 
                                                    value: "Not authorized"
                                            - pair(Type=MemberValuePair): 
                                                name(Type=SimpleName): 
                                                    identifier: "response"
                                                value(Type=ClassExpr): 
                                                    type(Type=ClassOrInterfaceType): 
                                                        name(Type=SimpleName): 
                                                            identifier: "ErrorResponse"
                                    - value(Type=NormalAnnotationExpr): 
                                        name(Type=Name): 
                                            identifier: "ApiResponse"
                                        pairs: 
                                            - pair(Type=MemberValuePair): 
                                                name(Type=SimpleName): 
                                                    identifier: "code"
                                                value(Type=IntegerLiteralExpr): 
                                                    value: "500"
                                            - pair(Type=MemberValuePair): 
                                                name(Type=SimpleName): 
                                                    identifier: "message"
                                                value(Type=StringLiteralExpr): 
                                                    value: "Internal error, see response for more details"
                                            - pair(Type=MemberValuePair): 
                                                name(Type=SimpleName): 
                                                    identifier: "response"
                                                value(Type=ClassExpr): 
                                                    type(Type=ClassOrInterfaceType): 
                                                        name(Type=SimpleName): 
                                                            identifier: "ErrorResponse"
                            name(Type=Name): 
                                identifier: "ApiResponses"
```

It tells me we have a list of annotations (`annotations:`). In it is this construction:

```yaml
   - annotation(Type=SingleMemberAnnotationExpr): 
                            memberValue(Type=ArrayInitializerExpr): 
                                values: 
                                    - value(Type=NormalAnnotationExpr): 
                                        name(Type=Name): 
                                            identifier: "ApiResponse"
                                        pairs: 
                                            - pair(Type=MemberValuePair): 
                                                name(Type=SimpleName): 
                                                    identifier: "code"
                                                value(Type=IntegerLiteralExpr): 
                                                    value: "200"
```
that you can read as...
"In the list of annotations, there is an annotation of type `SingleMemberAnnotationExpr` (you need instanceof and casting to find the right type) which I can as for its property `memberValue`. In this case it is an `ArrayInitializerExpr` (since there are multiple annotations within { } in the source code) which has a list of values. The first value is a `NormalAnnotationExpr` (need more casting here) that has a name and a list of "pairs". The name is simple to use, `asString` is useful here. It will get you "ApiResponse". In every pair we have a name and a value. In this case the name is "code", and the value, which can be any expression, is right now a literal integer (instanceof/casting maybe?) with value 200.

This is probably a lot more complex than what you expected, but I'm afraid Java is simply this complex.
