### ISSUE TITLE
class A extends B<T>.C parsing problem

### ISSUE THREAD

**Issue by Hanamaki** [javaparser/javaparser#1531]
I find a problem when I try to parse a class like `class A extends B<T>.C` to a `CompilationUnit`.
I just use the method that `JavaParser.parse(filepath)`.
Problem1: After parsing, it will be `class A extends B<T>.C<T>`
Problem2: The `C` is a static class in `B<T>`, so the type of `C` should be `ClassOrInterfaceType`, but after parsing, the `C` is a `SimpleName`.

Reason of Problem1: There is a node that `B<T>.C<T>`. Its scope is `B<T>`,its name is `C`, and it has a  typeArguments which is `T`.
Reason of Problem2: Sorry, I don't know that.

**Comment by matozoid** [comment]
Thanks! We'll look into it.

**Comment by matozoid** [comment]
When I run this:
```java
package com.github.javaparser.ast.type;

import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.printer.YamlPrinter;
import org.junit.Test;

import static com.github.javaparser.JavaParser.parse;

public class ClassOrInterfaceDeclarationTest {
    @Test
    public void issue1531() {
        CompilationUnit cu = parse("class A extends B<T>.C {}");
        System.out.println(new YamlPrinter(true).output(cu));
        System.out.println(cu);
    }
}
```
I get this:
```yaml
root(Type=CompilationUnit): 
    types: 
        - type(Type=ClassOrInterfaceDeclaration): 
            isInterface: "false"
            name(Type=SimpleName): 
                identifier: "A"
            extendedTypes: 
                - extendedType(Type=ClassOrInterfaceType): 
                    name(Type=SimpleName): 
                        identifier: "C"
                    scope(Type=ClassOrInterfaceType): 
                        name(Type=SimpleName): 
                            identifier: "B"
                        typeArguments: 
                            - typeArgument(Type=ClassOrInterfaceType): 
                                name(Type=SimpleName): 
                                    identifier: "T"
```
```java
class A extends B<T>.C {
}
```
... which looks fine to me. Can you change it to reproduce your issue?
