### ISSUE TITLE
Order of nodes in AST

### ISSUE THREAD

**Issue by villmow** [javaparser/javaparser#2172]
Hi, first of all very nice project! I'm currently analyzing ASTs with your tool and stumbled about the order of nodes in the AST when traversing it. 

See the following java code snippet: 
```java
public class Sample{
    public static double add(double a, double b) {
        return a + b;
    }
}
``` 
The parsed AST looks the following:
```yaml
root(Type=CompilationUnit): 
    types: 
        - type(Type=ClassOrInterfaceDeclaration): 
            isInterface: "false"
            name(Type=SimpleName): 
                identifier: "Sample"
            members: 
                - member(Type=MethodDeclaration): 
                    body(Type=BlockStmt): 
                        statements: 
                            - statement(Type=ReturnStmt): 
                                expression(Type=BinaryExpr): 
                                    operator: "PLUS"
                                    left(Type=NameExpr): 
                                        name(Type=SimpleName): 
                                            identifier: "a"
                                    right(Type=NameExpr): 
                                        name(Type=SimpleName): 
                                            identifier: "b"
                    type(Type=PrimitiveType): 
                        type: "DOUBLE"
                    name(Type=SimpleName): 
                        identifier: "add"
                    modifiers: 
                        - modifier(Type=Modifier): 
                            keyword: "PUBLIC"
                        - modifier(Type=Modifier): 
                            keyword: "STATIC"
                    parameters: 
                        - parameter(Type=Parameter): 
                            isVarArgs: "false"
                            name(Type=SimpleName): 
                                identifier: "a"
                            type(Type=PrimitiveType): 
                                type: "DOUBLE"
                        - parameter(Type=Parameter): 
                            isVarArgs: "false"
                            name(Type=SimpleName): 
                                identifier: "b"
                            type(Type=PrimitiveType): 
                                type: "DOUBLE"
            modifiers: 
                - modifier(Type=Modifier): 
                    keyword: "PUBLIC"
...
```
**Question:** Why is the methods body appearing before all other sibling nodes? When I traverse the tree depth first and preorder, I'd expect to see first the modifiers, then the method header and finally the body. See the [Java Grammar](https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-MethodDeclaration): 
```
MethodDeclaration:
    {MethodModifier} MethodHeader MethodBody
```

For clarity I'd expect the following output:
```yaml
[...]
- member(Type=MethodDeclaration): 
    modifiers: 
        - modifier(Type=Modifier): 
            keyword: "PUBLIC"
        - modifier(Type=Modifier): 
            keyword: "STATIC"
    type(Type=PrimitiveType): 
        type: "DOUBLE"
    name(Type=SimpleName): 
        identifier: "add"
    parameters: 
        - parameter(Type=Parameter): 
            isVarArgs: "false"
            name(Type=SimpleName): 
                identifier: "a"
            type(Type=PrimitiveType): 
                type: "DOUBLE"
        - parameter(Type=Parameter): 
            isVarArgs: "false"
            name(Type=SimpleName): 
                identifier: "b"
            type(Type=PrimitiveType): 
                type: "DOUBLE"
    body(Type=BlockStmt):
        statements:
            - statement(Type=ReturnStmt):
                expression(Type=BinaryExpr):
                    operator: "PLUS"
                    left(Type=NameExpr):
                        name(Type=SimpleName):
                            identifier: "a"
                    right(Type=NameExpr):
                        name(Type=SimpleName):
                            identifier: "b"
[...]
```

Am I doing something wrong, is there a way to traverse the AST pre-order depth first?

**Edit:** Btw.: Thats the code I used for parsing into YAML, but the same problem occurs when serializing to JSON: 
```java
CompilationUnit cu = StaticJavaParser.parse(method);
YamlPrinter printer = new YamlPrinter(true);
System.out.println(printer.output(cu));
```
