### ISSUE TITLE
IllegalStateException on Parameter.removeModifier

### ISSUE THREAD

**Issue by jlerbsc** [javaparser/javaparser#2184]
Hi,
I try to remove the final modifier in this code below

    catch (final CreateException e) {
        throw new Exception(e);
    }

    Parameter param = clause.getParameter();
    param.removeModifier(Modifier.Keyword.FINAL);

But it fails with the exception

    java.lang.IllegalStateException: Cannot keep element because we reached the end of nodetext: NodeText{[ChildTextElement{e}]}. Difference: Difference{[Removed{child(Modifier)}, Removed{token( )}, Kept{child(ClassOrInterfaceType)}, Kept{token( )}, Kept{child(SimpleName)}]}
    at com.github.javaparser.printer.lexicalpreservation.Difference.applyLeftOverDiffElements(Difference.java:180)
	at com.github.javaparser.printer.lexicalpreservation.Difference.apply(Difference.java:127)
	at com.github.javaparser.printer.lexicalpreservation.LexicalDifferenceCalculator.calculatePropertyChange(LexicalDifferenceCalculator.java:122)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$Observer.concretePropertyChange(LexicalPreservingPrinter.java:170)
	at com.github.javaparser.ast.observer.PropagatingAstObserver.propertyChange(PropagatingAstObserver.java:62)
...

I have the same exception if i try to add an annotation

    AnnotationExpr suppressWarning = new SingleMemberAnnotationExpr(new Name("SuppressWarnings"),
			new StringLiteralExpr("squid:S1166"));
    param.getAnnotations().add(suppressWarning);

in LexicalPreservingPrinter.concreteListChange(..) Difference.apply() generates this exception.

**Comment by matozoid** [comment]
Thanks!

**Comment by jlerbsc** [comment]
Here a test case

    AnnotationExpr suppressWarning = new SingleMemberAnnotationExpr(new Name("SuppressWarnings"),
    			new StringLiteralExpr("squid:S1166"));
    	
    	String sample = 
    			"try { /* nothing */ } \n" + 
    			"catch (final Exception e) { \n" +
    			"   System.out.println(\"This is an exception\"); \n" +
    			"}";

    	TryStmt stmt = TestParser.parseStatement(sample).asTryStmt();
    	stmt = LexicalPreservingPrinter.setup(stmt);
    	CatchClause cc = stmt.getCatchClauses().get(0);
        cc.getParameter().addAnnotation(suppressWarning);
        assertTrue(cc.getParameter().isAnnotationPresent("SuppressWarnings"));

It seems that when LexicalPreservingPrinter.getOrCreateNodeText(Node node) is called , the data of node parameter does not contain the modifier "final". So the action results in an exception 

    java.lang.IllegalStateException: Cannot keep element because we reached the end of nodetext: NodeText{[ChildTextElement{@SuppressWarnings("squid:S1166")}, " "   <1>   (?)-(?), ChildTextElement{Exception}, " "   <1>   (line 2,col 23)-(line 2,col 23), ChildTextElement{e}]}. Difference: Difference{[Added{child(SingleMemberAnnotationExpr)}, Added{token( )}, Kept{child(Modifier)}, Kept{token( )}, Kept{child(ClassOrInterfaceType)}, Kept{token( )}, Kept{child(SimpleName)}]}
	at com.github.javaparser.printer.lexicalpreservation.Difference.applyLeftOverDiffElements(Difference.java:179)
	at com.github.javaparser.printer.lexicalpreservation.Difference.apply(Difference.java:126)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$Observer.concreteListChange(LexicalPreservingPrinter.java:274)
	at com.github.javaparser.ast.observer.PropagatingAstObserver.listChange(PropagatingAstObserver.java:72)

After debugging a little, it seems that the modifier is not present in the data node because LexicalPreservingPrinter.storeInitialTextForOneNode(..) consider that the modifier is a Phantom Node. In fact, the range of the modifer node is not contained in the parent node range. I hope it can help you.

**Comment by matozoid** [comment]
Do you have an idea how this should be solved?

**Comment by jlerbsc** [comment]
Sorry, I have no idea otherwise I would have tried something. The issue seems to be in the generated code (this isn't LexicalPreservingPrinter issue) because after the parsing (TryStmt stmt = TestParser.parseStatement(sample).asTryStmt();), the parameter node of the CatchClause has a range (line 2,col 14)-(line 2,col 24) and tokenRange (Exception e) and the modifier node has a range (line 2,col 8)-(line 2,col 12) which is not included in the parameter node.

**Comment by matozoid** [comment]
```java
        TryStmt stmt = TestParser.parseStatement("try {} \n" +
                "catch (final Exception e) { \n" +
                "}").asTryStmt();
        System.out.println(new YamlPrinter(false).output(stmt));
```

```yaml
root: (line 1,col 1)-(line 3,col 1)
    tryBlock: (line 1,col 5)-(line 1,col 6)
    catchClauses: 
        - catchClause: (line 2,col 1)-(line 3,col 1)
            body: (line 2,col 27)-(line 3,col 1)
            parameter: (line 2,col 14)-(line 2,col 24)
                isVarArgs: "false"
                name: (line 2,col 24)-(line 2,col 24)
                    identifier: "e"
                type: (line 2,col 14)-(line 2,col 22)
                    name: (line 2,col 14)-(line 2,col 22)
                        identifier: "Exception"
                modifiers: 
                    - modifier: (line 2,col 8)-(line 2,col 12)
                        keyword: "FINAL"
```

**Comment by matozoid** [comment]
Hmmm, you're right.

**Comment by matozoid** [comment]
Can you check if the code in #2214 works for you? It changes the ranges as follows:
```yaml
root: (line 1,col 1)-(line 3,col 1)
    tryBlock: (line 1,col 5)-(line 1,col 6)
    catchClauses: 
        - catchClause: (line 2,col 1)-(line 3,col 1)
            body: (line 2,col 27)-(line 3,col 1)
            parameter: (line 2,col 7)-(line 2,col 24)
                isVarArgs: "false"
                name: (line 2,col 24)-(line 2,col 24)
                    identifier: "e"
                type: (line 2,col 14)-(line 2,col 22)
                    name: (line 2,col 14)-(line 2,col 22)
                        identifier: "Exception"
                modifiers: 
                    - modifier: (line 2,col 8)-(line 2,col 12)
                        keyword: "FINAL"
```
