### ISSUE TITLE
Add () as expression

### ISSUE THREAD

**Issue by abolfazl-sh** [javaparser/javaparser#3217]
Hello. does it possible add a method to do like this:
`Expression e = new BodyExp(BodyExp.parentheses, cExpression);`
for example above code make any wanted expression(here it's "cExpression") in parentheses.
BodyExp can contain "()" (and maybe"{}").
thanks a lot.

**Comment by jlerbsc** [comment]
There is already a BlockStmt. Does it not meet your needs?

**Comment by abolfazl-sh** [comment]
I checked it. it's for adding {}. I need () too.

**Comment by MysterAitch** [comment]
I think I understand, but would appreciate you sharing an example to be sure.

Do you want to do this, for example?

```java
// before
a + b

// after
(a + b)
```

What I recommend doing here is using JavaParser to create an AST of the before and after code, then compare to see the differences :)

This article may help:
https://javaparser.org/inspecting-an-ast/

As might this this plugin:
https://plugins.jetbrains.com/plugin/14245-javaparser-ast-inspector

**Comment by abolfazl-sh** [comment]
what I want is exactly what you say, but I didn't get your idea.
but I sure what you said don't help to modify AST . I want to make nested parentheses, something like below:
`((a + b) * ((x - y) + pow(x,2))) / (z * a)`
I have all the variables and I want to make above expression.(you know in fact I want to use parentheses to ordering some part of the code to use in future. it's a little hard to explain)
by the way thanks for answer.

**Comment by 4everTheOne** [comment]
Maybe [EnclosedExpr](https://www.javadoc.io/doc/com.github.javaparser/javaparser-core/latest/com/github/javaparser/ast/expr/EnclosedExpr.html) could help you with that. 

You can do something like:
```java
Expression before = StaticJavaParser.parseExpression("a + b"); //  a + b
Expression after = new EnclosedExpr(aPlusB);                   // (a + b)
```

And the result would match the provided by MysterAitch.

>
> // before
> a + b
> 
> // after
> (a + b)
>

**Comment by abolfazl-sh** [comment]
@4everTheOne, `EnclosedExpr` is exactly what I need. thanks a lot.

**Comment by MysterAitch** [comment]
> what I want is exactly what you say, but I didn't get your idea.

@abolfazl-sh - My comments above were a guide to export the parsed code as e.g. YAML or DOT for the "before" and "after", then compare the differences :+1: 

Once you know the type of node that you are trying to create, it becomes easy :smile: 


Here are some examples of the output you might see:


```java
int c = a + b;
```
```yaml
                            - statement(Type=ExpressionStmt): 
                                expression(Type=VariableDeclarationExpr): 
                                    variables: 
                                        - variable(Type=VariableDeclarator): 
                                            initializer(Type=BinaryExpr):  // Note here that the `initializer` is a `BinaryExpr`
                                                operator: "PLUS"
                                                left(Type=NameExpr): 
                                                    name(Type=SimpleName): 
                                                        identifier: "a"
                                                right(Type=NameExpr): 
                                                    name(Type=SimpleName): 
                                                        identifier: "b"
                                            name(Type=SimpleName): 
                                                identifier: "c"
                                            type(Type=PrimitiveType): 
                                                type: "INT"
```

```java
int d = (a + b);
```

```yaml
                            - statement(Type=ExpressionStmt): 
                                expression(Type=VariableDeclarationExpr): 
                                    variables: 
                                        - variable(Type=VariableDeclarator): 
                                            initializer(Type=EnclosedExpr): // Note here that the `initializer` is a `BinaryExpr` inside an `EnclosedExpr`
                                                inner(Type=BinaryExpr): 
                                                    operator: "PLUS"
                                                    left(Type=NameExpr): 
                                                        name(Type=SimpleName): 
                                                            identifier: "a"
                                                    right(Type=NameExpr): 
                                                        name(Type=SimpleName): 
                                                            identifier: "b"
                                            name(Type=SimpleName): 
                                                identifier: "d"
                                            type(Type=PrimitiveType): 
                                                type: "INT"
```


Here is a full class, output using a custom DOT format (makes it pretty colours) but the standard DOT printer output will give similar:

```java
class Scratch {
    public static void main(String[] args) {
        int a = 0;
        int b = 0;
        int c = a + b;
        int d = (a + b);
    }
}
```


Cropped image, showing just the side-by-side of `a+b` and `(a+b)` -- specifically note the `Initializer` of the `VariableDeclarator` within each:
![image](https://user-images.githubusercontent.com/1537214/113572408-102d9d00-9610-11eb-837c-266ee323ab87.png)

Full image:
![image](https://user-images.githubusercontent.com/1537214/113572294-d9578700-960f-11eb-886f-88a1339eba98.png)
